spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/harmony_users}
      auto-index-creation: false
      ssl: true
      ssl-invalid-host-name-allowed: true
      connect-timeout: 120000
      socket-timeout: 120000
      server-selection-timeout: 120000
      max-wait-time: 120000
      max-connection-pool-size: 10
      min-connection-pool-size: 1
      max-connection-idle-time: 30000
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key}
      expiration: 86400000 # 24 hours

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    mongo:
      enabled: true

logging:
  level:
    com.harmony: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.boot: DEBUG
    com.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true 