
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  eureka-server:
    build:
      context: ./backend/eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb

  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://mongodb:27017/user
    depends_on:
      - mongodb
      - eureka-server

  order-service:
    build:
      context: ./backend/order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://mongodb:27017/order
    depends_on:
      - mongodb
      - eureka-server

  product-service:
    build:
      context: ./backend/product-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://mongodb:27017/product
    depends_on:
      - mongodb
      - eureka-server

  notification-service:
    build:
      context: ./backend/notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://mongodb:27017/notification
    depends_on:
      - mongodb
      - eureka-server

volumes:
  mongo-data:
