version: '3.8'

services:
  # Frontend React App (Production)
  harmony-ui:
    build:
      context: ../../frontend/harmony-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://user-service-71511467925.europe-west1.run.app/api
        - REACT_APP_ENVIRONMENT=production
        - REACT_APP_VERSION=1.0.0
    container_name: harmony-ui-prod
    restart: unless-stopped
    ports:
      - "3001:8080"
    environment:
      - REACT_APP_API_URL=https://user-service-71511467925.europe-west1.run.app/api
      - REACT_APP_ENVIRONMENT=production
    networks:
      - harmony-network

networks:
  harmony-network:
    driver: bridge 