server:
  port: 8083

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/product}
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:8083

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.harmony: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
